[package]
name = "tensor"
version = "0.1.0"
edition = "2024"

[dependencies]
vknp_core = { path = "../core" }
core_types = { path = "../core-types" }
memory     = { path = "../memory" }
anyhow = { workspace = true }
pollster = { workspace = true }
bytemuck = { workspace = true }