[package]
name = "vknp_core"
version = "0.1.0"
edition = "2024"

[lib]
name = "vknp_core"
path = "src/lib.rs"

[dependencies]
wgpu = "26.0"
pollster = { workspace = true }
anyhow = { workspace = true }