[package]
name = "memory"
version = "0.1.0"
edition = "2024"

[dependencies]
vknp_core = { path = "../core" }
core_types = { path = "../core-types" }
pollster = { workspace = true }
bytemuck = { workspace = true }
anyhow = { workspace = true }